import { ArrowDown, ArrowUp, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, ErrorState, LoadingState } from '../common/States'
import { StatusBadge } from '../common/StatusBadge'
import type { OperationalRecord } from '../../types/personnel'
import type { PersonnelDirectoryItem } from '../../types/personnel'
import type { RiskExplanationResponse, RiskHistoryResponse, RiskPredictionResponse } from '../../types/risk'
import type { WellnessAssessment } from '../../types/wellness'
import type { WelfareAlert, WelfareRecommendation } from '../../types/welfare'

export function Panel({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-semibold text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{children}</section> }
export function SectionState({ state, message, empty = 'No welfare information available for this personnel record.', retry }: { state: 'loading' | 'error' | 'empty'; message?: string; empty?: string; retry?: () => void }) { if (state === 'loading') return <LoadingState />; if (state === 'error') return <ErrorState message={message} onRetry={retry} />; return <EmptyState title={empty} /> }
function tone(value?: string) { const v = value?.toUpperCase(); return v === 'HIGH' || v === 'PRIORITY' ? 'danger' : v === 'ELEVATED' || v === 'ATTENTION' ? 'warning' : 'success' }
export function RiskSummary({ data }: { data: RiskPredictionResponse }) { const category = data.risk_category; return <Panel title="Current Welfare Risk Indicator" description="This is a model-based welfare indicator intended to support human review. It is not a medical diagnosis or determination of fitness."><span className={`inline-flex rounded-lg px-4 py-2 text-lg font-bold tracking-wide ${category === 'HIGH' ? 'bg-rose-100 text-rose-900' : category === 'ELEVATED' ? 'bg-amber-100 text-amber-900' : 'bg-teal-100 text-teal-900'}`}>{category}</span><p className="mt-4 text-sm font-semibold text-slate-700">Current model probabilities</p><dl className="mt-2 grid gap-2 sm:grid-cols-3">{(['LOW', 'ELEVATED', 'HIGH'] as const).map(risk => <div key={risk} className="rounded-lg bg-slate-50 p-3 text-sm"><dt className="text-slate-600">{risk}</dt><dd className="mt-1 font-semibold">{(data.probabilities[risk] * 100).toFixed(1)}%</dd></div>)}</dl></Panel> }
export function RiskModelMetadata({ data }: { data: RiskPredictionResponse }) { const dataMode = data.data_mode === 'OPERATIONAL_ONLY' ? 'Operational data only' : 'Operational + voluntary wellness data'; return <Panel title="Risk model metadata"><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Model version</dt><dd className="mt-1 font-medium">{data.model_version}</dd></div><div><dt className="text-slate-500">Reference date</dt><dd className="mt-1 font-medium">{data.reference_date}</dd></div><div><dt className="text-slate-500">Data mode</dt><dd className="mt-1 font-medium">{dataMode}</dd></div></dl></Panel> }
export function Explanation({ data }: { data: RiskExplanationResponse }) { const explanation = data.explanation; const contributors = explanation?.top_contributors || []; return <Panel title="Model explanation" description="These factors describe how the model contributed to its current output. They do not establish causation or a medical diagnosis."><p className="mb-3 text-sm text-slate-600">Backend explanation for {explanation?.predicted_class || data.risk_category} · {explanation?.method || 'SHAP'}</p>{contributors.length ? <div className="divide-y divide-slate-100">{contributors.map((item, i) => { const increases = item.direction === 'increases_predicted_risk'; const decreases = item.direction === 'decreases_predicted_risk'; return <div key={`${item.feature}-${i}`} className="grid gap-2 py-3 sm:grid-cols-[minmax(10rem,0.8fr)_minmax(10rem,1.5fr)_minmax(8rem,0.7fr)] sm:items-center"><span className="text-sm font-medium text-slate-700">{item.label || item.feature}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100" role="img" aria-label={`${item.label || item.feature}: SHAP contribution ${item.shap_value}; ${item.direction}`}><div className={`h-full rounded-full ${increases ? 'bg-amber-500' : decreases ? 'bg-teal-700' : 'bg-slate-500'}`} style={{ width: `${Math.max(2, (Math.abs(item.shap_value) / Math.max(...contributors.map(contribution => Math.abs(contribution.shap_value)), Number.EPSILON)) * 100)}%` }} /></div><span className="flex items-center gap-1 text-xs text-slate-600">{increases ? <ArrowUp className="h-3.5 w-3.5 text-amber-700" /> : decreases ? <ArrowDown className="h-3.5 w-3.5 text-teal-800" /> : null}{item.shap_value} · {item.direction}</span></div> })}</div> : <EmptyState title="No risk explanation is currently available." />}</Panel> }
export function RiskHistory({ data, onPrevious, onNext }: { data: RiskHistoryResponse; onPrevious: () => void; onNext: () => void }) { const chronologicalItems = [...data.items].reverse(); const pages = Math.max(1, Math.ceil(data.total / data.page_size)); return <Panel title="Persisted Risk History" description="Historical model predictions saved by the backend. These records are not a clinical progression. ">{data.items.length ? <><ol aria-label="Historical risk predictions, chronological within this page" className="relative ml-2 border-l border-slate-200">{chronologicalItems.map((item, index) => <li className="mb-5 ml-5 last:mb-0" key={`${item.reference_date}-${index}`}><span className="absolute -left-1.5 mt-1.5 h-3 w-3 rounded-full border-2 border-white bg-teal-700" /><time className="text-sm text-slate-500">{item.reference_date}</time><p className="font-semibold text-slate-800">{item.risk_category}</p></li>)}</ol><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Historical persisted risk predictions</caption><thead><tr className="text-xs uppercase text-slate-500"><th className="py-2 pr-4">Reference date</th><th className="py-2 pr-4">Risk category</th></tr></thead><tbody>{data.items.map((item, index) => <tr key={`${item.reference_date}-row-${index}`} className="border-t border-slate-100"><td className="py-2 pr-4">{item.reference_date}</td><td className="py-2 pr-4 font-medium">{item.risk_category}</td></tr>)}</tbody></table></div></> : <EmptyState title="No historical risk predictions are available for this personnel record." />}<div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>Page {data.page} of {pages} · {data.total} prediction{data.total === 1 ? '' : 's'}</span><div className="flex gap-2"><button disabled={data.page <= 1} onClick={onPrevious} className="rounded-lg border border-slate-300 px-3 py-2 disabled:opacity-50">Previous</button><button disabled={data.page >= pages} onClick={onNext} className="rounded-lg border border-slate-300 px-3 py-2 disabled:opacity-50">Next</button></div></div></Panel> }
export function OperationalSummary({ records }: { records: OperationalRecord[] }) { const duty = records.filter(r => r.duty_hours != null); const night = records.filter(r => r.night_duty); const workload = records.filter(r => r.workload_score != null); const consecutive = records.filter(r => r.consecutive_duty_days != null); const avg = (values: number[]) => values.length ? (values.reduce((a, b) => a + b, 0) / values.length).toFixed(1) : 'Not available'; return <Panel title="Operational welfare context" description="Indicators returned by the personnel operational records."><div className="grid gap-3 sm:grid-cols-2"><Metric label="Average duty hours" value={avg(duty.map(r => r.duty_hours as number))} /><Metric label="Night duty records" value={night.length ? String(night.length) : 'Not available'} /><Metric label="Average workload" value={avg(workload.map(r => r.workload_score as number))} /><Metric label="Consecutive duty" value={avg(consecutive.map(r => r.consecutive_duty_days as number))} /></div></Panel> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-slate-200 p-4"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-slate-950">{value}</p></div> }
export function WellnessSummary({ assessments }: { assessments: WellnessAssessment[] }) { const latest = assessments[0]; return <Panel title="Voluntary wellness information" description="This information is consent-dependent and is shown only when permitted by the backend.">{latest ? <div className="grid gap-3 sm:grid-cols-2"><Metric label="Assessment date" value={latest.assessment_date} /><Metric label="Sleep quality" value={String(latest.sleep_quality)} /><Metric label="Fatigue level" value={String(latest.fatigue_level)} /><Metric label="Perceived stress" value={String(latest.perceived_stress)} /></div> : <EmptyState title="Voluntary wellness information unavailable" />}</Panel> }
export function Recommendations({ items }: { items: WelfareRecommendation[] }) { return <Panel title="Welfare-support guidance" description="Recommendations are support guidance, not disciplinary instructions.">{items.length ? <div className="space-y-3">{items.map((item, i) => <div key={i} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge label={item.category || 'Category unavailable'} tone="neutral" />{item.priority && <StatusBadge label={item.priority} tone={tone(item.priority)} />}</div><p className="mt-2 text-sm font-medium text-slate-800">{item.action || item.recommendation || 'Recommendation unavailable'}</p>{item.rationale && <p className="mt-1 text-xs text-slate-500">{item.rationale}</p>}</div>)}</div> : <EmptyState title="No welfare recommendations available" />}</Panel> }
export function Alerts({ alerts }: { alerts: WelfareAlert[] }) { return <Panel title="Workflow alerts" description="Alert severity is separate from the welfare risk category.">{alerts.length ? <div className="space-y-3">{alerts.map(alert => <div key={alert.alert_id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 p-4"><div><div className="flex items-center gap-2"><StatusBadge label={alert.severity} tone={tone(alert.severity)} /><span className="text-sm font-medium text-slate-800">{alert.status}</span></div><p className="mt-2 text-xs text-slate-500">{alert.persistence_reason || alert.trigger_type || 'Welfare workflow alert'} · {alert.created_at}</p></div><span className="text-xs text-slate-500">{alert.alert_id}</span></div>)}</div> : <EmptyState title="No welfare alerts available" />}</Panel> }
export function PrivacyNotice() { return <div className="flex gap-3 rounded-xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-teal-700" /><div><p className="font-semibold">Privacy Protected</p><p className="mt-1 leading-5">Access is role-controlled. Wellness information is consent-dependent. SURAKSHAI is designed for welfare support, not disciplinary action.</p></div></div> }
export function PersonnelLinks({ personnel }: { personnel: PersonnelDirectoryItem[] }) { return personnel.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Personnel reference</th><th className="px-3 py-3">Unit</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{personnel.map(person => <tr key={person.personnel_id}><td className="px-3 py-4 font-medium text-slate-800">{person.pseudonymous_reference || person.personnel_id}</td><td className="px-3 py-4 text-slate-600">{person.unit_id || 'Not available'}</td><td className="px-3 py-4 text-slate-600">{person.status || 'Not available'}</td><td className="px-3 py-4"><Link className="font-semibold text-teal-800 hover:underline" to={`/welfare/personnel/${encodeURIComponent(person.personnel_id)}`}>Open case</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No personnel references available">No authorized personnel records were returned by the directory.</EmptyState> }
export function ProtectedIcon() { return <ShieldCheck className="h-5 w-5 text-teal-700" /> }
